### PR TITLE
"page has no context" issue

### PR DESCRIPTION
**Pull request by leonardoballand**
- Fix "page has no context" error
- Remove unused routes import (minor update)
- Fix Firebase import (minor update)

### CODE REVIEW

**Comment by rwieruch** [comment]
I asked for help in my Slack Community, because I will find only time end of the week to review this. Thanks for all your help @leonardoballand 🚀

**Comment by rwieruch** [comment]
Unfortunately it doesn't work on my machine:

```
● server █████████████████████████ compiling (0%)


/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/webpack/lib/ProgressPlugin.js:205
				compilation.hooks.addEntry.tap("ProgressPlugin", entryAdd);
				                           ^

TypeError: Cannot read property 'tap' of undefined
    at compiler.hooks.compilation.tap.compilation (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/webpack/lib/ProgressPlugin.js:205:32)
    at SyncHook.eval [as call] (eval at create (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/next/node_modules/webpack/lib/Compiler.js:498:26)
    at hooks.beforeCompile.callAsync.err (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/next/node_modules/webpack/lib/Compiler.js:534:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/next/node_modules/webpack/lib/Compiler.js:529:28)
    at compiler.hooks.watchRun.callAsync.err (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/next/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/next/node_modules/webpack/lib/Watching.js:40:32)
    at Watching.compiler.readRecords.err (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/next/node_modules/webpack/lib/Watching.js:32:9)
    at Array.inputFileSystem.stat.err (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/next/node_modules/webpack/lib/Compiler.js:401:20)
    at Storage.finished (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/mydspr/Developer/Repos/nextjs-redux-firebase-authentication/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-nextjs-firebase-authentication@0.1.0 dev: `next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-nextjs-firebase-authentication@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mydspr/.npm/_logs/2018-11-14T02_35_11_758Z-debug.log
```

**Comment by rwieruch** [comment]
Someone else checked the PR and ran into one minor issue: https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/issues/6 Let's address this before merging the PR.

**Comment by leonardoballand** [comment]
Ok, I'm on it Robin!

Le mar. 11 déc. 2018 à 03:44, Robin Wieruch <notifications@github.com> a
écrit :

**Comment by rwieruch** [comment]
Fixed over here: https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pull/7 Thanks for everyone working on this issue!

**Pull request closed without merging**
